import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Boxes, Check, LogIn, Package, ShieldCheck, Trash2, Users } from "lucide-react";
import { Link } from "wouter";
import { formatZAR } from "@shared/nexusData";

export default function Admin() {
  const { user, loading } = useAuth();
  const [notice, setNotice] = useState("");
  const [stockDrafts, setStockDrafts] = useState<Record<number, number>>({});
  const products = trpc.admin.products.useQuery(undefined, { enabled: user?.role === "admin" });
  const users = trpc.admin.users.useQuery(undefined, { enabled: user?.role === "admin" });
  const orders = trpc.orders.adminList.useQuery(undefined, { enabled: user?.role === "admin" });
  const deleteProduct = trpc.admin.deleteProduct.useMutation({ onSuccess: () => { setNotice("Product removed from catalogue."); products.refetch(); } });
  const updateProduct = trpc.admin.updateProduct.useMutation({ onSuccess: () => { setNotice("Inventory updated."); products.refetch(); } });
  if (loading) return <div className="admin-gate">Loading NEXUS workspace…</div>;
  if (!user) return <div className="admin-gate"><LogIn size={30} /><h1>Sign in to continue</h1><p>Administrator access is protected by the NEXUS identity layer.</p><a className="primary-button" href="/api/oauth/login">SIGN IN <ShieldCheck size={17} /></a></div>;
  if (user.role !== "admin") return <div className="admin-gate"><ShieldCheck size={30} /><h1>Access restricted.</h1><p>This workspace is reserved for NEXUS administrators.</p><Link href="/"><span className="text-button">RETURN TO STOREFRONT <ArrowLeft size={16} /></span></Link></div>;
  return <div className="admin-page"><header className="admin-header"><div><p className="kicker">NEXUS / OPERATIONS</p><h1>Admin workspace.</h1></div><Link href="/"><span className="text-button"><ArrowLeft size={15} /> STOREFRONT</span></Link></header>{notice && <div className="admin-notice"><Check size={15} /> {notice}</div>}<div className="admin-stats"><div><Boxes size={17} /><span>CATALOGUE</span><strong>{products.data?.length ?? 0}</strong></div><div><Users size={17} /><span>USERS</span><strong>{users.data?.length ?? 0}</strong></div><div><Package size={17} /><span>ORDERS</span><strong>{orders.data?.length ?? 0}</strong></div></div><section className="admin-table"><div className="admin-table-head"><div><p className="kicker">INVENTORY / LIVE</p><h2>Product control</h2></div><span className="availability"><i /> CONNECTED TO DATABASE</span></div><div className="admin-rows">{products.data?.map((product) => <div className="admin-row" key={product.id}><div><span>{product.brand}</span><strong>{product.name}</strong></div><span>{formatZAR(Number(product.priceZar))}</span><span>{product.stock} IN STOCK</span><div className="admin-actions"><input className="stock-input" type="number" min="0" value={stockDrafts[product.id] ?? product.stock} onChange={(event) => setStockDrafts((current) => ({ ...current, [product.id]: Math.max(0, Number(event.target.value)) }))} aria-label={`Set stock for ${product.name}`} /><button className="text-button" onClick={() => updateProduct.mutate({ id: product.id, data: { stock: stockDrafts[product.id] ?? product.stock } })}>SET STOCK</button><button className="delete-button" onClick={() => deleteProduct.mutate({ id: product.id })} aria-label={`Delete ${product.name}`}><Trash2 size={15} /></button></div></div>)}</div></section><div className="admin-dual"><section className="admin-table"><div className="admin-table-head"><div><p className="kicker">ORDERS / LIVE</p><h2>Recent orders</h2></div></div>{orders.data?.length ? orders.data.map((order) => <div className="admin-mini-row" key={order.id}><strong>#{order.id.toString().padStart(4, "0")}</strong><span>{order.status.toUpperCase()}</span><span>{formatZAR(Number(order.totalZar))}</span></div>) : <p className="admin-muted">No orders have been confirmed yet.</p>}</section><section className="admin-table"><div className="admin-table-head"><div><p className="kicker">USERS / LIVE</p><h2>Members</h2></div></div>{users.data?.map((member) => <div className="admin-mini-row" key={member.id}><strong>{member.name || "NEXUS member"}</strong><span>{member.email || "—"}</span><span>{member.role.toUpperCase()}</span></div>)}</section></div></div>;
}
