import { Alert, Pressable, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useStore } from "@/context/store";

export default function CartScreen() {
  const { bag, userToken, add, decrement, remove, subtotal } = useStore();
  const checkout = async () => { if (!userToken) return Alert.alert("Sign in required", "Please sign in from the Profile tab before making a purchase."); const response = await fetch(`${process.env.EXPO_PUBLIC_API_URL ?? "http://localhost:3000/api"}/orders`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${userToken}` }, body: JSON.stringify({ items: bag.map(line => ({ productId: line.id, quantity: line.quantity })) }) }); const data = await response.json(); if (!response.ok) return Alert.alert("Checkout unavailable", data.error ?? "Please review your bag."); Alert.alert("Order confirmed", `Order #${data.orderId} · R ${Number(data.totalZar).toLocaleString("en-ZA")}`); };
  return <ScreenContainer className="flex-1 bg-[#F5EFC6] px-5 pt-8" edges={["top", "left", "right"]}><Text className="text-xs tracking-[3px] text-[#4D0E12]">YOUR BAG</Text><Text className="mt-3 text-4xl font-semibold text-[#231815]">Ready when you are.</Text>{bag.length === 0 ? <View className="mt-10 rounded-lg bg-[#231815] p-6"><Text className="text-lg font-semibold text-[#F5EFC6]">Your bag is empty.</Text><Text className="mt-2 leading-5 text-[#4A2E27]">Add considered objects from the Home tab.</Text></View> : bag.map(line => <View key={line.id} className="mt-4 rounded-lg bg-[#231815] p-5"><Text className="text-base font-semibold text-[#F5EFC6]">{line.name}</Text><Text className="mt-2 text-[#F5EFC6]">R {Number(line.priceZar).toLocaleString("en-ZA")}</Text><View className="mt-4 flex-row items-center gap-3"><Pressable onPress={() => decrement(line.id)} className="rounded bg-[#A5BCD6] px-3 py-2"><Text className="text-[#F5EFC6]">−</Text></Pressable><Text className="text-[#F5EFC6]">{line.quantity}</Text><Pressable onPress={() => add(line)} disabled={line.quantity >= line.stock} className="rounded bg-[#A5BCD6] px-3 py-2"><Text className="text-[#F5EFC6]">+</Text></Pressable><Pressable onPress={() => remove(line.id)} className="ml-auto"><Text className="text-[#4A2E27]">REMOVE</Text></Pressable></View><Text className="mt-2 text-xs text-[#4A2E27]">{line.stock - line.quantity} remaining after this quantity</Text></View>)}<View className="mt-auto border-t border-[#4A2E27] py-6"><View className="flex-row justify-between"><Text className="text-base text-[#A5BCD6]">Subtotal</Text><Text className="text-xl font-semibold text-[#231815]">R {subtotal.toLocaleString("en-ZA")}</Text></View><Pressable onPress={checkout} disabled={bag.length === 0} className="mt-4 rounded bg-[#231815] p-4"><Text className="text-center text-sm font-semibold tracking-[2px] text-[#F5EFC6]">{userToken ? "CHECKOUT" : "SIGN IN TO PURCHASE"}</Text></Pressable></View></ScreenContainer>;
}
