import { useEffect, useState } from "react";
import { Alert, FlatList, Pressable, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useStore } from "@/context/store";

const API_URL = process.env.EXPO_PUBLIC_API_URL ?? "http://localhost:3000/api";
type Product = { id: number; name: string; stock: number };

export default function ProfileScreen() {
  const { userToken, userRole, signIn, signOut } = useStore();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [registering, setRegistering] = useState(false);
  const [adminProducts, setAdminProducts] = useState<Product[]>([]);
  const submit = async () => { try { const response = await fetch(`${API_URL}/auth/${registering ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(registering ? { name, email, password } : { email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Authentication failed"); await signIn(data.token, data.user.role); Alert.alert("Welcome to NEXUS", "You can now continue to purchase from your bag."); } catch (error) { Alert.alert("Could not sign in", error instanceof Error ? error.message : "Please try again."); } };
  useEffect(() => { if (userToken && userRole === "admin") fetch(`${API_URL}/items`).then(response => response.json()).then(data => setAdminProducts(data.items ?? [])); }, [userRole, userToken]);
  const setStock = async (product: Product, stock: number) => { const response = await fetch(`${API_URL}/items/${product.id}`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${userToken}` }, body: JSON.stringify({ stock: Math.max(0, stock) }) }); if (response.ok) setAdminProducts(current => current.map(item => item.id === product.id ? { ...item, stock: Math.max(0, stock) } : item)); };
  return <ScreenContainer className="flex-1 bg-[#F5EFC6] px-5 pt-8" edges={["top", "left", "right"]}><Text className="text-xs tracking-[3px] text-[#4D0E12]">NEXUS ACCOUNT</Text><Text className="mt-3 text-4xl font-semibold text-[#231815]">Your edit.</Text>{userToken ? <><View className="mt-8 rounded-lg bg-[#231815] p-6"><Text className="text-lg font-semibold text-[#F5EFC6]">You are signed in.</Text><Text className="mt-2 leading-5 text-[#4A2E27]">Your purchase access is unlocked for this session.</Text><Pressable onPress={signOut} className="mt-6 rounded bg-[#F5EFC6] p-4"><Text className="text-center text-sm font-semibold tracking-[2px] text-[#231815]">SIGN OUT</Text></Pressable></View>{userRole === "admin" && <View className="mt-5 flex-1"><Text className="text-xs tracking-[3px] text-[#4D0E12]">ADMIN / STOCK CONTROL</Text><Text className="mt-2 text-2xl font-semibold text-[#231815]">Set remaining units.</Text><FlatList className="mt-4" data={adminProducts} keyExtractor={item => String(item.id)} contentContainerStyle={{ gap: 10, paddingBottom: 24 }} renderItem={({ item }) => <View className="rounded-lg bg-[#A5BCD6] p-4"><Text className="font-semibold text-[#F5EFC6]">{item.name}</Text><View className="mt-3 flex-row items-center justify-between"><Text className="text-[#4A2E27]">{item.stock} left</Text><View className="flex-row gap-2"><Pressable onPress={() => setStock(item, item.stock - 1)} className="rounded bg-[#231815] px-3 py-2"><Text className="text-[#F5EFC6]">−</Text></Pressable><Pressable onPress={() => setStock(item, item.stock + 1)} className="rounded bg-[#F5EFC6] px-3 py-2"><Text className="text-[#231815]">+</Text></Pressable></View></View></View>} /></View>}</> : <View className="mt-8 rounded-lg bg-[#231815] p-6"><Text className="text-lg font-semibold text-[#F5EFC6]">{registering ? "Create your NEXUS account." : "Sign in to purchase."}</Text>{registering && <TextInput value={name} onChangeText={setName} placeholder="Name" placeholderTextColor="#4A2E27" className="mt-5 rounded bg-[#A5BCD6] px-4 py-3 text-[#F5EFC6]" />}<TextInput value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" keyboardType="email-address" placeholderTextColor="#4A2E27" className="mt-3 rounded bg-[#A5BCD6] px-4 py-3 text-[#F5EFC6]" /><TextInput value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry placeholderTextColor="#4A2E27" className="mt-3 rounded bg-[#A5BCD6] px-4 py-3 text-[#F5EFC6]" /><Pressable onPress={submit} className="mt-5 rounded bg-[#F5EFC6] p-4"><Text className="text-center text-sm font-semibold tracking-[2px] text-[#231815]">{registering ? "REGISTER" : "SIGN IN"}</Text></Pressable><Pressable onPress={() => setRegistering(value => !value)} className="mt-4"><Text className="text-center text-[#4A2E27]">{registering ? "Already have an account? Sign in" : "New to NEXUS? Create an account"}</Text></Pressable></View>}</ScreenContainer>;
}
